export const MultiAgentes = [
  {
    domain: 'frontend',
    keywords: [
      'frontend',
      'react',
      'nextjs',
      'vuejs',
      'angular',
      'tela',
      'página web',
    ],
    agents: [
      {
        name: 'backlog',
        keywords: [
          'backlog',
          'história',
          'épico',
          'story',
          'criar backlog',
          'escrever histórias',
          'história de usuário',
        ],
      },
      {
        name: 'architecture',
        keywords: [
          'estrutura de pastas',
          'organização',
          'componentização',
          'como estruturar o front',
          'padrão de pastas',
        ],
      },
      {
        name: 'documentation',
        keywords: [
          'documentação',
          'documentar',
          'doc front',
          'documentar front',
          'criar documentação',
          'docs do front',
          'explicar componentes',
        ],
      },
      {
        name: 'review',
        keywords: [
          'revisão front',
          'review front',
          'checar front',
          'revisar código front',
          'review de tela',
          'checar front',
          'melhorar código front',
        ],
      },
    ],
  },

  {
    domain: 'database',
    keywords: [
      'database',
      'banco de dados',
      'modelagem de dados',
      'criar tabelas',
      'banco',
      'sql',
      'mysql',
      'postgres',
      'postgresql',
      'mongodb',
      'nosql',
      'tabela',
      'relacional',
      'modelagem',
      'schema',
      'migrations',
      'orm',
    ],
    agents: [
      {
        name: 'analyze-database',
        keywords: [
          'analisar banco',
          'modelar banco',
          'normalização',
          'otimizar banco',
          'estrutura de dados',
          'ajustar tabelas',
          'otimizar consultas',
          'desenhar estrutura de dados',
          'normalizar',
        ],
      },
    ],
  },

  {
    domain: 'ux',
    keywords: [
      'ux',
      'ui',
      'experiência do usuário',
      'interface do usuário',
      'user experience',
      'user interface',
      'layout',
      'wireframe',
      'protótipo',
      'figma',
      'melhorar a tela',
      'organizar fluxo',
    ],
    agents: [
      {
        name: 'generate',
        keywords: [
          'ux writing',
          'fluxo do usuário',
          'prototipação',
          'navegação',
          'usabilidade',
          'prototipar',
          'melhorar usabilidade',
          'navegação do usuário',
          'analisar UX',
        ],
      },
    ],
  },

  {
    domain: 'qa',
    keywords: [
      'qa',
      'qualidade',
      'testes',
      'testar',
      'automação de testes',
      'selenium',
      'cypress',
      'playwright',
      'pytest',
      'cenários',
      'casos de teste',
      'tester',
      'quality assurance',
    ],
    agents: [
      {
        name: 'generate',
        keywords: [
          'plano de teste',
          'roteiro de teste',
          'testcase',
          'automation test',
          'robot framework',
          'reproduzir bug',
          'reportar bug',
        ],
      },
    ],
  },

  {
    domain: 'backend',
    keywords: [
      'backend',
      'nodejs',
      'express',
      'java',
      'spring',
      'python',
      'flask',
      'django',
      'api',
      'rest',
      'graphql',
      'servidor',
    ],
    agents: [
      {
        name: 'api/planner',
        keywords: ['planejamento api', 'mapear endpoints', 'design de rotas'],
      },
      {
        name: 'api/coder',
        keywords: [
          'arquitetura backend',
          'microservices',
          'services',
          'repositories',
          'mvc',
        ],
      },
      {
        name: 'api/tester',
        keywords: ['swagger', 'openapi', 'testar api'],
      },
      {
        name: 'api/review',
        keywords: ['review backend', 'refatorar backend', 'segurança backend'],
      },
    ],
  },
  {
    domain: 'devops',
    keywords: [
      'devops',
      'ci',
      'cd',
      'cicd',
      'pipeline',
      'deploy',
      'docker',
      'container',
      'kubernetes',
      'cluster',
      'helm',
      'terraform',
      'iac',
      'infra',
      'nginx',
      'load balancer',
      'monitoramento',
      'observabilidade',
      'prometheus',
      'grafana',
      'logging',
      'devsecops',
      'segurança devops',
    ],
    agents: [
      {
        name: 'backlog',
        keywords: [
          'infraestrutura',
          'servidor',
          'cloud',
          'aws',
          'gcp',
          'azure',
          'terraform',
          'iac',
          'rede',
          'dns',
          'load balancer',
          'escalabilidade',
        ],
      },
      {
        name: 'architecture',
        keywords: [
          'ci',
          'cd',
          'pipeline',
          'github actions',
          'gitlab ci',
          'jenkins',
          'deploy automático',
          'rollback',
          'workflow devops',
        ],
      },
      {
        name: 'documentation',
        keywords: [
          'logs',
          'monitoramento',
          'alertas',
          'metrics',
          'observabilidade',
          'prometheus',
          'grafana',
          'opentelemetry',
          'tracing',
        ],
      },
      {
        name: 'review',
        keywords: [
          'devsecops',
          'segurança',
          'hardening',
          'vulnerabilidade',
          'owasp',
          'segurança de pipeline',
          'segurança de container',
        ],
      },
    ],
  },
];
